error: Increase the number of fields transmitted through IPROTO
Has been added IPROTO_ERROR_TRACEBACK and IPROTO_ERROR_CUSTOM_TYPE
fields to IPROTO_ERROR_STACK for transfering through network
a backtrace and custom type.

Needed for #4398