error: Add a Lua backtrace to error
In accordance with https://github.com/tarantool/tarantool/issues/4398
Lua traceback has been added for box.error.
Has been added a per server flag for turn on/off traceback adding
and ability to force it at creation time.

@TarantoolBot document
Title: error.traceback
Was added:
Per server flag for turn on/off adding a traceback to the errors.
box.error.cfg({traceback_supplementation = true/false})
Adding a traceback can be forced on creation.
box.error.new({type = "CustomType", reason = "reason", traceback = true/false})

Needed for #4398