error: Add the custom error type
A possibility to create an error with a custom subtype was added.

In accordance with https://github.com/tarantool/tarantool/issues/4398
a custom error type has been added to the box.error.
Now, it's possible to create an error with a custom subtype (string value)
for use it in applications.

@TarantoolBot document
Title: error.custom_type
A custom error type has been added to the box.error.
Now, it's possible to create an error with a custom subtype (string value)
for use it in applications.

To API has been added:
- For create CustomError: box.error.new(type(str), format, ...)
                          box.error.new({type = str,
                                         reason = str})

- error.type - CustomType error return custom type
    other errors return "base" error tybe
- base_type - return "base" errror type
Example:

err_custom = box.error.new("My Custom Type", "Reason")
Now:
err_custom.type == "My Custom Type"
err_custom.base_type == "CustomType"
err_custom.message == "Reason"

Needed for #4398